spring:
  application:
    name: social-wall

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

app:
  uploads:
    directory: uploads